In [1]:
from tensorflow import keras as kr

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('train.tsv', sep='\t')

In [4]:
df.head()

PhraseId  SentenceId                                             Phrase   
0         1           1  A series of escapades demonstrating the adage ...  \
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

In [5]:
reviews = df['Phrase']
labels = df['Sentiment']

In [6]:
Vocab_size = 200
encoded_reviews = [kr.preprocessing.text.one_hot(d,Vocab_size) for d in reviews]
print(f'encoded reviews: {encoded_reviews}')

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [7]:
max_length = 40
padded_reviews = kr.preprocessing.sequence.pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[117  41  18 ...   0   0   0]
 [117  41  18 ...   0   0   0]
 [117  41   0 ...   0   0   0]
 ...
 [109  12   0 ...   0   0   0]
 [109   0   0 ...   0   0   0]
 [ 12   0   0 ...   0   0   0]]


# RNN

In [20]:
model = kr.models.Sequential()

model.add(kr.layers.Embedding(input_dim=Vocab_size, output_dim=8, input_length=max_length))
model.add(kr.layers.SimpleRNN(50))
model.add(kr.layers.Dense(50, activation=kr.activations.relu))
model.add(kr.layers.Dense(5, activation=kr.activations.softmax))

model.compile(optimizer=kr.optimizers.Adam(), loss=kr.losses.sparse_categorical_crossentropy, metrics = [kr.metrics.sparse_categorical_accuracy])

In [ ]:
model.fit(padded_reviews, labels, batch_size=256, epochs=3)

Epoch 1/3
332/610 [===============>..............] - ETA: 15s - loss: 1.2940 - sparse_categorical_accuracy: 0.5078

# GRU

In [8]:
model = kr.models.Sequential()

model.add(kr.layers.Embedding(input_dim=Vocab_size, output_dim=8, input_length=max_length))
model.add(kr.layers.GRU(50))
model.add(kr.layers.Dense(50, activation=kr.activations.relu))
model.add(kr.layers.Dense(5, activation=kr.activations.softmax))

model.compile(optimizer=kr.optimizers.Adam(), loss=kr.losses.sparse_categorical_crossentropy, metrics = [kr.metrics.sparse_categorical_accuracy])

In [9]:
model.fit(padded_reviews,labels,epochs=100,verbose=1)

Epoch 1/100
4471/4877 [==========================>...] - ETA: 3s - loss: 1.2176 - sparse_categorical_accuracy: 0.5148

KeyboardInterrupt: 

# LSTM

In [8]:
model = kr.models.Sequential()

model.add(kr.layers.Embedding(input_dim=Vocab_size, output_dim=8, input_length=max_length))
model.add(kr.layers.LSTM(50, dropout=.2, recurrent_dropout=.2))
model.add(kr.layers.Dense(50, activation=kr.activations.relu))
model.add(kr.layers.Dense(5, activation=kr.activations.softmax))

model.compile(optimizer=kr.optimizers.Adam(), loss=kr.losses.sparse_categorical_crossentropy, metrics = [kr.metrics.sparse_categorical_accuracy])

In [ ]:
model.fit(padded_reviews,labels,epochs=100,verbose=1)

Epoch 1/100
 310/4877 [>.............................] - ETA: 54s - loss: 1.3118 - sparse_categorical_accuracy: 0.5029

In [12]:
model = Sequential()
embedding_layer = Embedding(input_dim=Vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(LSTM(50, dropout=0.2, recurrent_dropout=0.2))
#model.add(Flatten())
model.add(Dense(5,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 40, 8)             1600      
                                                                 
 lstm_1 (LSTM)               (None, 50)                11800     
                                                                 
 dense_1 (Dense)             (None, 5)                 255       
                                                                 
Total params: 13,655
Trainable params: 13,655
Non-trainable params: 0
_________________________________________________________________
None
